### ISSUE TITLE
学习了~~~加油！

### ISSUE THREAD

**Issue by hanhaotian** [gaussic/SpringMVCDemo#1]
正在看连载哦····写的真好··！受益颇多~~~谢谢

在添加博客的时候遇到了400错误怎么破？查看博客详情什么的都是ok的0.0
出了俩400错误   添加新博文，以及更新博文时候

其他都一切正常
请问是因为   提交时  某个参数为空，所以报错么？

**Comment by gaussic** [comment]
最好把报错信息贴出来吧，因为无法知道是哪个参数为空，我觉得有可能是发布日期的问题，这一点不太好处理的。

**Comment by hanhaotian** [comment]
HTTP Status 400 -
type Status report
message
description The request sent by the client was syntactically incorrect.
百度到的说法：1.客户端发送的请求语法错误（但是我仔细检查了代码，参数名都对着）
                         2.也有说是某个参数为空了
                         3.Spring在转换日期出错了
但是据说在spring-framework-reference.pdf找到下面这几行代码,加到自己的Action里，问题就解决了。如果真能解决这几行代码该往哪贴呢？
@InitBinder  
public void initBinder(WebDataBinder binder) {  
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
    dateFormat.setLenient(false);  
    binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, false));
