### ISSUE TITLE
500问题解决办法

### ISSUE THREAD

**Issue by HappyDoyourself** [gaussic/SpringMVCDemo#21]
按照步骤，我昨天在自己的机器上也是出现了500 的问题，和其他人的一模一样。于是今天来公司后又在公司重新部署了下，发现和昨天晚上的几个不一样的地方：
1.右键项目，选择Add Framework Support：
下拉选择JavaEE Persistence，右边provider选择Hibernate：
选择 user library  
 后 我本机上没有自动出现这个hibernate的maven 包。而是提示我DownLoad lib 包。 当时检查了好久这个问题，仍是不知道为什么不出现。甚至重新再来了一次不出现这个maven依赖包。而今天在公司部署时候直接出来了。
2.view-Tool windows-Persistence ，右键项目名，选择Generate Persistence Mapping，再选择By Database Schema：出现了 Import Database Schema 这个后，按照教程配置后，最后点ok的时候，和教程有点不一样：最下面的Generation Settings 的下面第一个复选框 Add to  Persistence Unit  要选上，并且自定义一个名字，这个名字 对应mvc-dispatcher-servlet.xml 的 persistenceUnitName 后面的value值。
教程上面的是defaultPersistenceUnit。
3.我自己机器使用的jdk1.8 ，在公司使用的是jdk1.7 。
  

  这个是我本机和在公司配置的不同，希望有帮助。

**Comment by HappyDoyourself** [comment]
![qq 20170322105928](https://cloud.githubusercontent.com/assets/26371413/24180228/b60de192-0eee-11e7-98b1-a7a5ed16b097.png)

**Comment by HappyDoyourself** [comment]
![qq 20170322110534](https://cloud.githubusercontent.com/assets/26371413/24180377/8fa4b8ea-0eef-11e7-8c5b-1cd3a493146e.png)

**Comment by gaussic** [comment]
你好，IDEA的升级很快，可能会发生部分的变化。
