### ISSUE TITLE
我如果想在jsp页面显示图片，该怎么实现啊

### ISSUE THREAD

**Issue by th0o0** [gaussic/SpringMVCDemo#26]
@gaussic 

`<src="/admin/11.png"/>`我在blogs.jsp里面加入这句代码，显示不了图片（11.png和blogs.jsp在同一个目录）
在这里没有改变什么   mvc-dispatcher-servlet.xml

**Comment by th0o0** [comment]
@gaussic 
我已经实现了，发现自己对路径还不理解和项目各个文件夹的意义不太清楚

**Comment by gaussic** [comment]
```
<!--静态资源(js、image等)的访问 -->
<mvc:default-servlet-handler/>
```

这一条，是默认的静态资源访问的配置，它会从webapp目录下开始找，因此，你要把所有的文件放在webapp目录下，然后根据路径来访问

**Comment by th0o0** [comment]
@gaussic 
`<!--<mvc:resources mapping="/public/**" location="/public/" />-->`
我在 xml 下面这样写，也可以这样访问静态资源，这两者有什么区别么！

对servlet 从哪里开始访问路径的我还是不太明白，可以指导一下么，谢谢了

**Comment by gaussic** [comment]
两者都可以，第一种是简化版本，第二种可以指定目录

**Comment by th0o0** [comment]
@gaussic 
`<mvc:default-servlet-handler/>`
这种简化的是不是默认的从webapp 目录下面开始扫描静态文件的

**Comment by gaussic** [comment]
多尝试以下就知道了

**Comment by th0o0** [comment]
ok，谢了
