### ISSUE TITLE
修改blog的时候会出现报错

### ISSUE THREAD

**Issue by personman941220** [gaussic/SpringMVCDemo#27]
org.apache.jasper.JasperException: /WEB-INF/pages/admin/updateBlog.jsp (line: 50, column: 26) According to TLD or attribute directive in tag file, attribute value does not accept any expressions
网上提示是因为jstl版本问题，或者是没有使用RT库。。。。

**Comment by gaussic** [comment]
你看看你的jstl版本和我是否一致

**Comment by personman941220** [comment]
版本是一样的，就是不支持Date哪里的fmt标签，一用就会报错，没有用那个就可以正常修改了。

**Comment by gaussic** [comment]
@personman941220 爱莫能助，试试用其他的方法显示日期看

**Comment by personman941220** [comment]
额，那您那边还有别的项目可供学习的么？有个问题我想问问，就是这个blog的如果设置用户登陆的话 要怎么拦截其它的页面请求呢？

**Comment by gaussic** [comment]
spring 有监听请求的机制的，需要进行一些配置。翻翻文档，需要一个listener拦截页面，检测用户是否登录（一般登录信息放在cookie中，你可以用HttpSession把用户名放到session里面，然后检测是否存在）。
最笨的方法就是在每个方法里面添加 if(session.getAttribute("xxx") !== null && session.getAttribute("xxx") =="yyy") 来验证是否登录，如果未登录就拒绝或者直接跳转到登录页面。

**Comment by gaussic** [comment]
http://spring.io/guides  推荐你看这里面的教程，现在官方更加推崇用 spring boot 搭建应用

**Comment by personman941220** [comment]
但是我感觉我英语水平不足，还有其他教程么？还是说只能硬啃。

**Comment by gaussic** [comment]
https://course.tianmaying.com/web-development  那你还是看这个吧

**Comment by personman941220** [comment]
万分感谢。
