### ISSUE TITLE
HTTP Status 400 -

### ISSUE THREAD

**Issue by hanhaotian** [gaussic/SpringMVCDemo#3]
HTTP Status 400 -
type Status report
message
description The request sent by the client was syntactically incorrect.
百度到的说法：1.客户端发送的请求语法错误（但是我仔细检查了代码，参数名都对着）
2.也有说是某个参数为空了
3.Spring在转换日期出错了
但是据说在spring-framework-reference.pdf找到下面这几行代码,加到自己的Action里，问题就解决了。如果真能解决这几行代码该往哪贴呢？
@InitBinder

public void initBinder(WebDataBinder binder) {

SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

dateFormat.setLenient(false);

binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, false));

**Comment by hanhaotian** [comment]
我在BlogControl中添加了
 @InitBinder
    public void initBinder(WebDataBinder binder) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);
        binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, true));
    }
然后在mvc-dispatcher-servlet.xml中添加了
  
    <bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
        <property name="messageConverters">
            <list>
                <ref bean="stringHttpMessageConverter"/>
            </list>
        </property>
    </bean>
    
    <bean id="stringHttpMessageConverter" class="org.springframework.http.converter.StringHttpMessageConverter"/>
之后，修改Blog好了  但是还是不能添加，一添加就继续报400错误

**Comment by hanhaotian** [comment]
<bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
        <property name="messageConverters">
            <list>
                <ref bean="stringHttpMessageConverter"/>
            </list>
        </property>
    </bean>
    
    <bean id="stringHttpMessageConverter" class="org.springframework.http.converter.StringHttpMessageConverter"/>

**Comment by hanhaotian** [comment]
<bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
        <property name="messageConverters">
            <list>
                <ref bean="stringHttpMessageConverter"/>
            </list>
        </property>
    </bean>




<bean id="stringHttpMessageConverter" class="org.springframework.http.converter.StringHttpMessageConverter"/>

**Comment by gaussic** [comment]
按道理来说，如果是Date的话，应该是不需要这个@InitBinder的。之前做的一个项目，因为要传TimeStamp类型的数据，所以才用到了@InitBinder，在Controller里加了：

```
@InitBinder
    public void binder(WebDataBinder binder) {binder.registerCustomEditor(Timestamp.class,
            new PropertyEditorSupport() {
                public void setAsText(String value) {
                    try {
                        Date parsedDate = new SimpleDateFormat("yyyy-MM-dd HH:mm").parse(value);
                        setValue(new Timestamp(parsedDate.getTime()));
                    } catch (ParseException e) {
                        setValue(null);
                    }
                }
            });
    }
```

另外，报错信息不一定是网页里面的，你看看下面位置的报错然后贴出来
![tomcat](https://cloud.githubusercontent.com/assets/12946979/15453545/69e6395e-204c-11e6-87ac-be26acb214f0.png)

你尝试着 下载我的项目，看看跑起来有什么问题

**Comment by hanhaotian** [comment]
五月 22, 2016 10:17:53 下午 org.apache.catalina.core.ApplicationContext log
信息: No Spring WebApplicationInitializer types detected on classpath
五月 22, 2016 10:17:53 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring FrameworkServlet 'mvc-dispatcher'

五月 22, 2016 10:17:50 下午 org.apache.catalina.core.AprLifecycleListener init
信息: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: D:\WorkPlace\Java\jdk1.8.0_65\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;D:\WorkPlace\Oracle\product\11.2.0\dbhome_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;D:\WorkPlace\Matlab\runtime\win64;D:\WorkPlace\Matlab\bin;D:\WorkPlace\Java\jdk1.8.0_65\bin;D:\WorkPlace\Java\jdk1.8.0_65\jre\bin;D:\WorkPlace\Java\apache-maven-3.3.9\bin;D:\WorkPlace\mysql-5.6.26-winx64\bin;;.
五月 22, 2016 10:17:50 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-bio-8080"]
五月 22, 2016 10:17:50 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["ajp-bio-8009"]
五月 22, 2016 10:17:50 下午 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 858 ms
五月 22, 2016 10:17:50 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service Catalina
五月 22, 2016 10:17:50 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet Engine: Apache Tomcat/7.0.52
五月 22, 2016 10:17:50 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-bio-8080"]
五月 22, 2016 10:17:50 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["ajp-bio-8009"]
五月 22, 2016 10:17:50 下午 org.apache.catalina.startup.Catalina start
信息: Server startup in 108 ms
五月 22, 2016 10:17:51 下午 org.apache.catalina.loader.WebappClassLoader validateJarFile
信息: validateJarFile(F:\workplace\Intellij  Projects\MyBlog\target\MyBlog\WEB-INF\lib\servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
五月 22, 2016 10:17:51 下午 org.apache.catalina.deploy.WebXml setVersion
**警告: Unknown version string [3.1]. Default version will be used.**
五月 22, 2016 10:18:00 下午 org.apache.catalina.startup.HostConfig deployDirectory
信息: Deploying web application directory D:\WorkPlace\Tomcat\webapps\manager
五月 22, 2016 10:18:05 下午 org.apache.jasper.compiler.TldLocationsCache tldScanJar
看起来这个好像没什么错误

你的项目我跑了报500错误，servlet mvc-dispatcher 貌似我没改好  

HTTP Status 500 - Servlet.init() for servlet mvc-dispatcher threw exception

type Exception report

message Servlet.init() for servlet mvc-dispatcher threw exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet.init() for servlet mvc-dispatcher threw exception
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)
root cause

java.lang.IllegalArgumentException
    org.springframework.asm.ClassReader.<init>(Unknown Source)
    org.springframework.asm.ClassReader.<init>(Unknown Source)
    org.springframework.asm.ClassReader.<init>(Unknown Source)
    org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:52)
    org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
    org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
    org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:76)
    org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:298)
    org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:300)
    org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:300)
    org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:230)
    org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:153)
    org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:130)
    org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:285)
    org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:223)
    org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
    org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
    org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:647)
    org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:598)
    org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:661)
    org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:517)
    org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:458)
    org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:138)
    javax.servlet.GenericServlet.init(GenericServlet.java:158)
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 logs.

**Comment by gaussic** [comment]
除了显示了一条参数非法，其他无法看出什么具体的问题，恕我愚钝。

这样吧，你把你的项目打包一份上传网盘给我看看，注意不要项目里面的target文件夹。

**Comment by hanhaotian** [comment]
链接：http://pan.baidu.com/s/1gfEvxIF 密码：hkh2

实在是太感谢你啦！！！麻烦了

**Comment by gaussic** [comment]
你在 addBlog.jsp 的 form 里面多了一行：
![addblog](https://cloud.githubusercontent.com/assets/12946979/15477845/92fffb2e-2149-11e6-939e-dc8dd23cfd8b.png)

把 input 删掉就可以了，你这样应该是复制 updateUser的时候，连带复制过来的。所以显示了这个非法参数。

**Comment by hanhaotian** [comment]
呃  .....这个其实是我之前以为是空参的问题从addUser那特意拷过来的。哈哈   那这样的话就应该是有了@InitBinder就解决了！我就说怎么修改可以了，增加还是不行。原来是之前乱修改的后遗症！！！太感谢你了！入门教程全靠你啦~~~
