### ISSUE TITLE
根据帖子上的教程，没有生成Webapp目录

### ISSUE THREAD

**Issue by JayvinPan** [gaussic/SpringMVCDemo#31]
我在OS China上按照您的帖子上面做，在
“ 菜单File->New Project可进入上图界面，首先选择左边栏Maven，再配置JDK（一般如果之前添加了JDK的话会自动填充，如未添加的话点击旁边的New将JDK目录导入即可）。勾选“Create from archetype“，然后选中4处蓝色位置webapp，点Next，进入如下界面 ”
这个步骤中没有找到在哪勾选蓝色位置的webapp(OS China上的图片显示不了)，下面附上截图：
![image](https://user-images.githubusercontent.com/26504333/27823661-7ee087ca-60dc-11e7-9c0c-fc4597fb925d.png)

**Comment by gaussic** [comment]
真大眼睛找找看

**Comment by JayvinPan** [comment]
能给张图片吗，我看论坛上的图片是没加载出来的

**Comment by gaussic** [comment]
![233218_v1av_2287879](https://user-images.githubusercontent.com/12946979/27845193-3559424e-615f-11e7-81b5-a8980fa2b72e.png)

**Comment by JayvinPan** [comment]
感谢博主
