### ISSUE TITLE
添加中文500

### ISSUE THREAD

**Issue by XiaoChenYung** [gaussic/SpringMVCDemo#7]
添加用户如果有中文会报500错误
04-Sep-2016 11:11:10.989 WARN [http-nio-8080-exec-7] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions SQL Error: 1366, SQLState: HY000
04-Sep-2016 11:11:10.990 ERROR [http-nio-8080-exec-7] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions Incorrect string value: '\xE5\x98\xBF\xE5\x98\xBF' for column 'first_name' at row 1
04-Sep-2016 11:21:02.531 WARN [http-nio-8080-exec-9] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions SQL Error: 1366, SQLState: HY000
04-Sep-2016 11:21:02.533 ERROR [http-nio-8080-exec-9] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions Incorrect string value: '\xE9\x98\xBF\xE4\xB8\x89' for column 'first_name' at row 1

**Comment by gaussic** [comment]
@XiaoChenYung ，在创建数据库的时候，是不是没有选择UTF-8，最好选择 utf8-unicode_ci格式
![we](http://7xqclt.com1.z0.glb.clouddn.com/1.png)

**Comment by XiaoChenYung** [comment]
好的
